# Generated by Django 3.0.5 on 2020-11-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='ISO',
        ),
        migrations.RemoveField(
            model_name='image',
            name='exposure',
        ),
        migrations.RemoveField(
            model_name='image',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='image',
            name='whitebal',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
